// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouqypmfkbnzpjdhrfdis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cXlwbWZrYm56cGpkaHJmZGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ0NjUsImV4cCI6MjA3Mzc5MDQ2NX0.hcE9-7RD-UtOKEGrHvVAeFGjGCbpDrJiLizcP20Eh8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});